### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by hamxahbhatti** [omarsou/layoutlm_CORD#3]
I am using your provided layoutlm notebook for training the dataset that you have shared but when i am doing training  i am getting this error of CUDA error: device-side assert triggered at 0 epochs. Can you please upload the latest working code. Thanks.

![image](https://user-images.githubusercontent.com/34483870/120093387-5a745b80-c133-11eb-9f45-29bdf013105c.png)

**Comment by GK4444** [comment]
did u use generate_dataset.ipynb, because in that file while creating pickle files the bbox were added in [x1, y3, x3, y1] format which was throwing the error, when changed to [x1,y1,x3,y3] works for me.
